In [2]:
import numpy as np

In [3]:
marks=np.array([88,90,30,45,75])

In [4]:
marks=marks+5

In [5]:
marks-15

array([78, 80, 20, 35, 65])

In [6]:
print(marks)

[93 95 35 50 80]


In [7]:
marks>=45

array([ True,  True, False,  True,  True])

Indexing

In [8]:
# accessed using both positive and negative indexing
marks[3]

50

Traversing

In [9]:
for i in range(len(marks)):
    print(marks[i])

93
95
35
50
80


Slicing

In [10]:
marks[2:]

array([35, 50, 80])

2D Array

In [11]:
marks=np.array([[85,78,90],[92,85,98],[76,82,80]])
print(marks)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


2D Slicing

In [12]:
marks[0:2]
marks[0:2,0:2]

array([[85, 78],
       [92, 85]])

In [13]:
print(marks[0,2])
print(marks[1,0:2])
print(marks[1][0:2])

90
[92 85]
[92 85]


In [14]:
marks[1][2]

98

In [15]:
print(marks[1:,1])
print(marks[1:][1])

[85 82]
[76 82 80]


Concatenation

In [16]:
b1=np.array([56,78,89])
b2=np.array([65,76,98])

comb1=np.concatenate((b1,b2))
print(comb1)

[56 78 89 65 76 98]


2D Concatenation 

In [17]:
b1=np.array([[56,78,89],[34,45,67]])
b2=np.array([[65,76,98],[89,98,78]])

comb2=np.concatenate((b1,b2))
print(comb2)

[[56 78 89]
 [34 45 67]
 [65 76 98]
 [89 98 78]]


In [18]:
b1=np.array([[56,78,89],[34,45,67]])
b2=np.array([[65,76,98],[89,98,78]])

comb2=np.concatenate((b1,b2),axis=1)
print(comb2)

[[56 78 89 65 76 98]
 [34 45 67 89 98 78]]


Split - divides array in equal division

In [19]:
np.split(comb1,3)

[array([56, 78]), array([89, 65]), array([76, 98])]

Search

In [20]:
print(marks)
print(np.where(marks==98))
print(np.where(marks>=80))
print(marks[np.where(marks>=80)])

[[85 78 90]
 [92 85 98]
 [76 82 80]]
(array([1], dtype=int64), array([2], dtype=int64))
(array([0, 0, 1, 1, 1, 2, 2], dtype=int64), array([0, 2, 0, 1, 2, 1, 2], dtype=int64))
[85 90 92 85 98 82 80]


Sorting

In [21]:
print(np.sort(marks))
print(np.sort(marks)[::-1])

[[78 85 90]
 [85 92 98]
 [76 80 82]]
[[76 80 82]
 [85 92 98]
 [78 85 90]]


In [22]:
print(marks)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [23]:
print(np.sort(marks,axis=1))

[[78 85 90]
 [85 92 98]
 [76 80 82]]


In [24]:
print(np.sort(marks,axis=0))

[[76 78 80]
 [85 82 90]
 [92 85 98]]


In [27]:
arr=np.array(['name',85, True, 5.5])
print(type(arr[2]))

<class 'numpy.str_'>
